name: Mucky Cow
favicon: null
layout_spectrum: 0.09409123472869396
typography_spectrum: 0.49152909708209336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06140689877793193
  lightness: 0.20188017911277711
  saturation: 0.8011425922159106
  rhythmicContrast: 0.4691359871067107
purpose: []
